apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app1
spec:
  selector:
    matchLabels:
      app: flask-app1
  template:
    metadata:
      labels:
        app: flask-app1
    spec:
      containers:
      - name: flask-app1-container
        image: nileshdhakane/flask-app1:latest
        ports:
        - containerPort: 5000
